[BUG]: out of license

## Command Line
/home/kali/.local/bin/pyarmor gen encode_code.py

## Environments
Python 3.12.8
Pyarmor 9.0.7 (trial), 000000, non-profits
Platform linux.x86_64
Native linux.x86_64
Home /home/kali/.pyarmor

## Traceback
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.12/site-packages/pyarmor/cli/__main__.py", line 784, in main
    main_entry(sys.argv[1:])
  File "/home/kali/.local/lib/python3.12/site-packages/pyarmor/cli/__main__.py", line 777, in main_entry
    return args.func(ctx, args)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.12/site-packages/pyarmor/cli/__main__.py", line 245, in cmd_gen
    builder.process(options)
  File "/home/kali/.local/lib/python3.12/site-packages/pyarmor/cli/generate.py", line 188, in process
    self._obfuscate_scripts()
  File "/home/kali/.local/lib/python3.12/site-packages/pyarmor/cli/generate.py", line 144, in _obfuscate_scripts
    code = Pytransform3.generate_obfuscated_script(self.ctx, r)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.12/site-packages/pyarmor/cli/core/__init__.py", line 95, in generate_obfuscated_script
    return m.generate_obfuscated_script(ctx, res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<maker>", line 716, in generate_obfuscated_script
  File "/home/kali/.local/lib/python3.12/site-packages/pyarmor/cli/__init__.py", line 16, in process
    return meth(self, res, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<maker>", line 546, in process
  File "<maker>", line 552, in coserialize
  File "<maker>", line 597, in _build_ast_body
RuntimeError: out of license


